# Generated by Django 6.0.6 on 2026-07-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('GENERAL', 'General System Inquiry'), ('COLLAB', 'Technical Collaboration Proposal'), ('SUPPORT', 'Platform Bug/Support Ticket')], default='GENERAL', max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
